### ISSUE TITLE
Losing Messages

### ISSUE THREAD

**Issue by finleysg** [mkuthan/example-kafka#6]
I have used the sink + callback pattern outside of streaming in a Spark SQL job that publishes dataframe rows to Kafka. Now that I've moved the solution to our production environment, it appears that I am losing about 10 messages per 100000.

My guess is that a message in the tail end of each partition is not getting flushed to topic as a given batch job terminates. Does that make sense? Am I naive to use this pattern for a non-streaming scenario?

This is the primary method in our sink:

```
  def sendDeltasToKafka(dataframe: DataFrame, changeFlag: String, counter: LongAccumulator): Unit = {
    dataframe.foreachPartition { partitionRecords =>
      val producer = ProducerFactory.getOrCreateDeltaProducer(deltas)
      val context = TaskContext.get
      val schema: Schema = new Schema.Parser().parse(registeredSchema.schema)
      val keys = registeredDataset.keys.map(k => k.columnName)
      val writer = new AvroRowWriter(schema, keys)

      val callback = new KafkaSinkExceptionHandler

      logInfo(s"Sending Spark partition: ${context.partitionId} to Kafka topic: ${registeredDataset.kafkaTopic}")
      val metadata = partitionRecords.map { row =>
        callback.throwExceptionIfAny()

        val key = writer.GetKey(row)
        val record = writer.GetValue(row, changeFlag, auditTimestamp)
        val message = new ProducerRecord[String, Array[Byte]](registeredDataset.kafkaTopic, key, serialize(record, schema))

        counter.add(1)
        producer.send(message, callback)
      }.toList

      metadata.foreach { metadata => metadata.get() }
      logInfo(s"Flushed Spark partition: ${context.partitionId} to Kafka topic: ${registeredDataset.kafkaTopic}")

      callback.throwExceptionIfAny()
    }
  }
```

The callback class is exactly as you wrote it in your example.

**Comment by mkuthan** [comment]
Hi @finleysg 

I would verify the following concepts:

Ensure that the callback is implemented correctly. Check this commit with important fix:
https://github.com/mkuthan/example-spark-kafka/commit/1d2b23fc7af21bafebe056ebfe0b284ba756fc3d#diff-4d85d2d4621e183d3a1a49703ce9f48d

You could also flush messages using explicit method available since Kafka 0.9:
https://kafka.apache.org/10/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html

Finally verify that producer is closed properly during application shutdown. If not, pending messages will be lost.
https://github.com/mkuthan/example-spark-kafka/blob/e042a2d21085da48864b1a4775b86d3dee75160b/src/main/scala/org/mkuthan/spark/KafkaProducerFactory.scala#L46

Let me know if you find the reason of lost messages.

**Comment by finleysg** [comment]
Thank you. I am calling `producer.close()` in the shutdown hook in my producer factory, just as in your example. I have implemented the fix to the callback and set the `acks` setting to `all`. I will run some tests with a large dataframe to see if any exceptions are thrown that we were losing before.

**Comment by finleysg** [comment]
It looks like the callback fix + setting acks=all is working. I've not found any evidence of losing messages since I've made those changes.

**Comment by mkuthan** [comment]
Great, thanks for Your response!
